# @package _global_
defaults:
  - override /hydra/launcher: ray
  - override /hydra/sweeper: optuna


hydra:
  mode: "MULTIRUN"
  launcher:
    ray:
      remote:
        num_cpus: 5
      init:
        local_mode: false

  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    n_trials: 50
    n_jobs: 5
    direction: minimize

    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 1234
      n_startup_trials: 10
