defaults:
  - _self_

eval_callback:
  _target_: stable_baselines3.common.callbacks.EvalCallback
  callback_on_new_best:
    _target_: stable_baselines3.common.callbacks.StopTrainingOnRewardThreshold
    reward_threshold: 500
    verbose: 1
  eval_env: ${env.eval_env}
  best_model_save_path: ${checkpoint_path}/best_model
  log_path: ${checkpoint_path}/logs
  n_eval_episodes: 5
  eval_freq: 10000
  deterministic: true
  render: false
  verbose: 1




 
