
_target_: src.agents.flex_ppo.VarFlexPPO
policy: ${policy}
env: ${env.train_env}
learning_rate: 0.01
n_steps: 1024
batch_size: 256
gamma: 0.98
gae_lambda: 0.98
ent_coef: 0.0
clip_range: 0.13807904071618782
verbose: 1
tensorboard_log: ${tensorboard_path}
seed: ${seed}
device: cpu


